name:           Vanilla Template Sets
id:             vanilla-template-sets
key:            vanilla-template-sets
description:    The simplest Movable Type templates in HTML 1.0
version:        1.0
author_name:    Beau Smith
author_link:    http://www.beausmith.com/mt/
plugin_link:    http://www.beausmith.com/mt/plugins/vanilla

template_sets:
    vanilla:
        label: Vanilla
        base_path: templates/vanilla
        order: 501
        notes: 
            - Lastn entries on Homepage
            - Entry Detail for each
        templates:
            index:
                home:
                    label: Homepage
                    outfile: index.html
                    rebuild_me: 1
            individual:
                entry: 
                    label: Entry
                    mappings:
                        entry_archive:
                            archive_type: Individual
            module:
                wrapper:
                    label: Wrapper
    vanilla_archives:
        label: Vanilla + Archives
        base_path: templates/vanilla+archives
        notes:
            - Base homepage & entries
            - Archive Index
            - Archives: Monthly, Author, Category and Category-Monthly
            - Navigation w/ Category-Monthly links on Category Archives
        order: 502
        templates:
            index:
                home:
                    label: Homepage
                    outfile: index.html
                    rebuild_me: 1
                archives:
                    label: Archives
                    outfile: archives.html
                    rebuild_me: 1
            individual:
                entry: 
                    label: Entry
                    mappings:
                        entry_archive:
                            archive_type: Individual
            archive:
                entry_listing: 
                    label: Entry Listing
                    mappings:
                        monthly:
                            archive_type: Monthly
                        category:
                            archive_type: Category
                        category-monthly:
                            archive_type: Category-Monthly
                        author:
                            archive_type: Author
            module:
                wrapper:
                    label: Wrapper
    vanilla_pages:
        label: Vanilla + Pages
        base_path: templates/vanilla+pages
        notes:
            - Base homepage & entries
            - Pages
            - Navigation including Pages
        order: 503
        templates:
            index:
                home:
                    label: Homepage
                    outfile: index.html
                    rebuild_me: 1
            individual:
                entry: 
                    label: Entry
                    mappings:
                        entry_archive:
                            archive_type: Individual
            page:
                page: 
                    label: Page
                    mappings:
                        page_archive:
                            archive_type: Page
            module:
                wrapper:
                    label: Wrapper
    vanilla_authentication_userpics:
        label: Vanilla + Authentication & Userpics
        base_path: templates/vanilla+authentication+userpics
        notes: 
            - En/disable userpics in javascript
            - Use of community "edit profile" script is necessary to add userpics. The "edit profile" page assumes that you are using profiles and thus links to "view profile" screen. If using profiles is not desired, the "view profile" link can be removed from the "Profile Edit" Global System Template.
        order: 504
        templates:
            index:
                home:
                    label: Homepage
                    outfile: index.html
                    rebuild_me: 1
                javascript:
                    label: JavaScript
                    outfile: mt.js
                    rebuild_me: 1
            module:
                wrapper:
                    label: Wrapper
    vanilla_authentication_comments:
        label: Vanilla + Authentication & Comments
        base_path: templates/vanilla+authentication+comments
        notes:
            - foo
        order: 505
        templates:
            index:
                home:
                    label: Homepage
                    outfile: index.html
                    rebuild_me: 1
                javascript:
                    label: JavaScript
                    outfile: mt.js
                    rebuild_me: 1
            individual:
                entry: 
                    label: Entry
                    mappings:
                        entry_archive:
                            archive_type: Individual
            module:
                wrapper:
                    label: Wrapper
            system:
                comment_preview:
                    label: Comment Preview
                comment_response:
                    label: Comment Response
    vanilla_authentication_comments_userpics:
        label: Vanilla + Authentication & Comments w/ Userpics
        base_path: templates/vanilla+authentication+comments+userpics
        notes:
            - foo
        order: 506
        templates:
            index:
                home:
                    label: Homepage
                    outfile: index.html
                    rebuild_me: 1
                javascript:
                    label: JavaScript
                    outfile: mt.js
                    rebuild_me: 1
            individual:
                entry: 
                    label: Entry
                    mappings:
                        entry_archive:
                            archive_type: Individual
            module:
                wrapper:
                    label: Wrapper
            system:
                comment_preview:
                    label: Comment Preview
                comment_response:
                    label: Comment Response

# 
# - Organization
#     * Categories
#     * Tags
# - Create Entry
#     * category selector
#     vanilla:
#         label: 'Vanilla - Homepage + Entries'
#         base_path: 'templates/vanilla'
#         order: 100
#         templates:
# - Profiles + Userpics
#     * Userpics
#     * Profiles
#     vanilla:
#         label: 'Vanilla - Homepage + Entries'
#         base_path: 'templates/vanilla'
#         order: 100
#         templates:
# - Profiles + Friending
#     * Friending
#     vanilla:
#         label: 'Vanilla - Homepage + Entries'
#         base_path: 'templates/vanilla'
#         order: 100
#         templates:
# - Rating
#     * 1
#     * 5 Star
#     * -1, 0, 1
#     vanilla:
#         label: 'Vanilla - Homepage + Entries'
#         base_path: 'templates/vanilla'
#         order: 100
#         templates:
# - YUI Template
